version: 2.1
orbs:
  garnet: garnet/garnet-orb@0.0.2
jobs:
  run-garnet:
    docker:
      # replace with your preferred image
      - image: circleci/node:latest
    steps:
    - checkout
    - garnet/analyze
workflows:
  main-workflow:
    jobs:
      - run-garnet
